GRANT CONNECT ON DATABASE :db TO :user;
GRANT SELECT, TRIGGER ON TABLE "pipe_defects" TO :user;
GRANT SELECT, TRIGGER ON TABLE "mandrel_defects" TO :user;
GRANT SELECT, TRIGGER ON TABLE "billets" TO :user;
